### ISSUE TITLE
cloud-machine doesn't load the second disk ephemeral

### ISSUE THREAD

**Issue by lborguetti** [NeowayLabs/cloud-machine#2]
When an AMI instance has more than one ephemeral disk, cloud-machine doesn't load the second disk

cloud-machine  yml

```
instance:
  name: X-node
  type: c3.large
  imageid: ami-85ada4b5
  region: us-west-2
  defaultavailablezone: us-west-2a
  keyname: MY-KEY
  securitygroups: [sg-00000000]
  subnetid: subnet-00000000
  cloudconfig: cloud-config/x-node.yml
  ebsoptimized: false
```
