### ISSUE TITLE
cloud-machine don't work with multi-AZ deployment 

### ISSUE THREAD

**Issue by lborguetti** [NeowayLabs/cloud-machine#6]
`cloud-machine` always creates EBS at us-west-2a, falling when create EC2 instance in another AZ.

Example of machine-config:

```
instance:
  name: PREV-EC2-nat-node-001-2b
  subnetid: subnet-xxxxxxxx
  imageid: ami-e0342681
  region: us-west-2
  defaultavailablezone: us-west-2b
  keyname: xxx-xxxxxxxxxxx-key
  type: t2.medium
  cloudconfig: cloud-config/node.yaml
  ebsoptimized: false
  securitygroups: [sg-xxxxxxxx]

volumes:
  - name: PREV-EBS-node-data-001-2b
    type: gp2
    size: 10
    device: /dev/xvdk
    mount: /data
    filesystem: ext4
```
